### ISSUE TITLE
Linux build failed

### ISSUE THREAD

**Issue by VishnuEaswaran** [adhuliya/ajit-toolchain#1]
The Ajit custom Linux build fails; log files attached. Steps followed are

1. Sourced [old_ajit_repo_setup_paths.sh](https://github.com/adhuliya/ajit-toolchain/blob/d3dfc95428b2bbb842a2f0154366495712c240f8/from_ajit_repo/old_ajit_repo_setup_paths.sh)
2. ran the script [GeneratememMapForAjit.sh](https://github.com/adhuliya/ajit-toolchain/blob/d3dfc95428b2bbb842a2f0154366495712c240f8/from_ajit_repo/os/Ajit_linux/GeneratememMapForAjit.sh)

Brief overview running the script:

- step 1 ran successfully
- step 2 fails with error reporting missing file named Makefile.lib in the scripts directory within Linux source ([link](https://github.com/adhuliya/ajit-toolchain/tree/d3dfc95428b2bbb842a2f0154366495712c240f8/from_ajit_repo/os/Ajit_linux/Ajit_linux_3.16.1))
- step 3 ran successfully and created the device tree
- step 4 fails as it depends on the outputs of previous steps

**LOGFILE**: [link](https://drive.google.com/file/d/1akkcfT_sTb8X2GGJyYGAiGuMMmnwdg_j/view?usp=sharing)

**Comment by VishnuEaswaran** [comment]
My system settings

**Environment**: **ubuntu:16.04** image-based container with the help of Docker.
Additional packages added on top of the base image are

- build-essential
- rsync
- wget
- cpio
- unzip
- bc
- python
- python3
- libncurses5-dev
- device-tree-compiler
- bison
- flex
- libssl-dev

**Comment by VishnuEaswaran** [comment]
Gave missing lib libsigsegv-dev. Installed the same.

**Comment by VishnuEaswaran** [comment]
**Fresh build**: Attempt after pulling and merging the new changes & additions: [commit snapshot](https://github.com/adhuliya/ajit-toolchain/tree/dca508d5b589fb76dc2999e5abaa0f6bd2952f3b)

Ran _setup_ script from the top-most directory which ran successfully. Then sourced the _export_ script from _from_ajit_repo_ and further ran the _GeneratememMapForAjit.sh_ script.

**Result**: still failed at step2. Error hints a missing file called Makefile.lib.

![image](https://user-images.githubusercontent.com/3790701/92923835-b4be7680-f455-11ea-96a6-9387cf936fed.png)
(**please click on the image to view it properly**)

Log: [Log File](https://drive.google.com/file/d/1yUCRbRY1vN9X_ifLLV0osKhGI5b8bAt4/view?usp=sharing)

**Comment by VishnuEaswaran** [comment]
this [commit](https://github.com/adhuliya/ajit-toolchain/commit/ee5aec26181a802ab7c4d9723090afc4073c89ba) ~seems to~ have solved the missing file issue.

**Comment by VishnuEaswaran** [comment]
New build after fixing the missing Makefile.lib

Result : **failed**

- error in step 2 resulting in failed linux build. instances of error are as follows

![image](https://user-images.githubusercontent.com/3790701/93601208-73dada80-f9de-11ea-99a2-e40d672b6c4c.png)

![image](https://user-images.githubusercontent.com/3790701/93601292-9b31a780-f9de-11ea-8e71-267053eb7007.png)

- errors in step 5 

![image](https://user-images.githubusercontent.com/3790701/93601350-b3092b80-f9de-11ea-8a10-8393f1008c66.png)

here, the first _cp_ error is because of the missing _Generated_memory_map_ directory.

last error is because of the failed step 2.

**log file** - [link](https://drive.google.com/file/d/1psxFJZUB_HpHQtLJEC7Ieu_9cJ_v1TBL/view?usp=sharing)

**Comment by VishnuEaswaran** [comment]
vmlinux.lds.S seems to be the ld script for the kernel. Yet again, that particular file is missing in our source. I noticed there is a gitignore in the directory where script is supposed to be present, that intentionally ignores vmlinux.lds. But the file missing is vmlinux.lds.S which makes makes things more confusing.

path to the script: Ajit_linux_3.16.1/arch/sparc/kernel/
repo link to the path: [link](https://github.com/adhuliya/ajit-toolchain/tree/cc987234ebaabc760a6eed95bab0add153818340/from_ajit_repo/os/Ajit_linux/Ajit_linux_3.16.1/arch/sparc/kernel)

**Comment by VishnuEaswaran** [comment]
Tried building the image by copying the mentioned file from [here](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/sparc/kernel/vmlinux.lds.S?h=v3.16.1).

Result: no errors noticed after fixing the missing _Generated_memory_map _ directory.
Conclusion: Not sure if this is the right solution. Someone should look into this.

**Comment by adhuliya** [comment]
I had not been involved in the linux kernel part of the project yet. Hence most of the stuff mentioned here is alien to me. Thanks for the effort to resolve the issue on your own. I will start looking into this and get back soon.

**Comment by VishnuEaswaran** [comment]
I noticed that [here](https://github.com/adhuliya/ajit-toolchain/blob/83ff2393032fe20db00f84e7bd4ff3f86fa7affa/from_ajit_repo/os/Ajit_linux/AJITREFS.txt#L197l) a change in vmlinux.lds is mentioned

**Comment by adhuliya** [comment]
I am a bit delayed on this issue. I am trying to get the grip on the three main components of the build process: buildroot-2014.08, ajit_C_system_model, and the supporting build scripts. As I see since this issue is not a show stopper right now, once these three are properly in shape and reliably reproducible (possibly in a docker image), I will get back to this issue.

**Comment by adhuliya** [comment]
I am back on this issue and will update soon. Hopefully with a readable build instructions on the marshal branch.

**Comment by VishnuEaswaran** [comment]
Linux has been building successfully for a long time now.
