### ISSUE TITLE
Docker build failure

### ISSUE THREAD

**Issue by VishnuEaswaran** [adhuliya/ajit-toolchain#11]
The docker build is failing. Out of three images, only _ajit_base_ is getting built. I tried the build in a fresh, shallow clone of _marshal_ and here is the log. 

[docker_build.zip](https://github.com/adhuliya/ajit-toolchain/files/5535750/docker_build.zip)

here is my `docker images` output

![screenshot](https://user-images.githubusercontent.com/3790701/99049061-64ca7000-25bc-11eb-88c1-76e94b41e31b.png)

**Comment by adhuliya** [comment]
I expected something like this to popup. Actually the `.so` files are not meant to be in the repo but are still
needed for some hacky build scripts. I have amended `.gitignore` to include libSockPipes.so file in the repo,
please pull the latest commit and try it again.

PS: What is meant by a 'shallow' clone of marshal?

**Comment by VishnuEaswaran** [comment]
Okay, that sounds like the culprit. 

Shallow clone is just cloning the repo without all the history. In my case I choose the "depth" as 1, which is the number of commits and related data to fetch from the current head, and selectively cloned just the marshal branch. Shallow cloning comes very handy when the repo is huge along with the history.

**Comment by adhuliya** [comment]
I am hoping that the docker setup went well. Hence closing the issue.

Thanks for sharing information on shallow clone. I had never used it before.

**Comment by VishnuEaswaran** [comment]
I haven't touched the repo this whole week. Will update this first thing tomorrow.

**Comment by VishnuEaswaran** [comment]
It seems some part of the bug still persist. I cloned the branch again today, removed all the prebuilt images and stages, then tried building but still encountered errors. The good news is that the _base and build_ images are built successfully while the build_tools is failing. I am attaching the log and screenshot of `docker images`

![image](https://user-images.githubusercontent.com/3790701/99938022-01df9280-2d8d-11eb-8095-59e561a8aae1.png)

[log.zip](https://github.com/adhuliya/ajit-toolchain/files/5581508/log.zip)

**Comment by VishnuEaswaran** [comment]
UPDATE: Today I ran the script and it ran without issues. I will try once again and report here later; I hope the issue is resolved.

**Comment by VishnuEaswaran** [comment]
weirdly the very first run fail to build ajit_tools but the subsequent execution succeed. I don't know how to pin down what is wrong. Help needed.

**Comment by adhuliya** [comment]
I will try to do a fresh build and see if I can reproduce the issue.

**Comment by VishnuEaswaran** [comment]
I am getting a new error this time when I rebuild everything for my fresh OS install (Xubuntu 20.04). I couldn't find the mentioned script in ajit_build image too

![image](https://user-images.githubusercontent.com/3790701/101117649-75936200-360d-11eb-9f9d-7c1e97152adb.png)

[log_xubuntu.zip](https://github.com/adhuliya/ajit-toolchain/files/5640396/log_xubuntu.zip)

**Comment by adhuliya** [comment]
I have fixed it. However, you shouldn't be getting this error unless the line with `exit;` in the `docker_setup.sh` is commented out.
Right now my efforts are focused on ajit_build_dev with is getting built successfully as printed in your logs.
I have made more improvements to the image and building process with some finer adjustments to
the user permissions etc. Please use the next commit where I will mention this issue.

**Comment by VishnuEaswaran** [comment]
Thank you @adhuliya. Yes this error occur while building ajit_tools. I will pull the commits and use hem in future,

**Comment by adhuliya** [comment]
@VishnuEaswaran The issues raised here are quite helpful to make the tool-chain robust. Thanks for the prompt support and communication.
