### ISSUE TITLE
trouble with building device tree compiler

### ISSUE THREAD

**Issue by saurabhb17** [adhuliya/ajit-toolchain#13]
While compiling device tree compiler in marshal branch, I faced issues because bison and flex were not installed.
That has been fixed by changing setup_ajit_base.sh in docker/ajit_base/

procedure to install deviceTreeCompiler is to run
1. make
2. make install 
in the ../tools/deviceTreeCompiler/ directory

make works fine, though make install throws an error: 

```
/usr/bin/install: cannot change permissions of '/home/ajit/bin': No such file or directory
Makefile:164: recipe for target 'install-bin' failed
make: *** [install-bin] Error 1

```

**Comment by adhuliya** [comment]
@saurabhb17 I have added the building of the device tree. You can invoke the same within docker by going to `scripts/build_tools.sh` script. I have avoided using `make install`, but added the necessary paths to the PATH and the LD_LIBRARY_PATH variable to use the device tree compiler. Please check the same from your end.

As currently I have little idea about the use of the component, please feel free to comment on the purpose of the paths in the `ajit_env` file and commit the changes. I have mentioned you at some places in the ajit_env file to write some readable comment in there.

**Comment by VishnuEaswaran** [comment]
Zombie issue. dtc builds fine.
