### ISSUE TITLE
Linux build in docker setup

### ISSUE THREAD

**Issue by saurabhb17** [adhuliya/ajit-toolchain#14]
In a new branch, branched off from marshal, I have added the OS related stuff.

Steps on how to build the Linux image are mentioned in a README placed at os/ directory.

In few steps of this process, I am getting the following error multiple times :
`File /tmp/objdump-trace.txt open error with error number 24.`

The log of this complete build obtained, was added in the commit 54ddca39f9267649a26b5dfaabc64faefb05dfce

**Comment by saurabhb17** [comment]
I have tested the linux image on the fpga card and got kernel panic error, please advise on how to resolve it.


Linux boot log attached
[linuxBootWithMarshal_bin-utils.log](https://github.com/adhuliya/ajit-toolchain/files/5864411/linuxBootWithMarshal_bin-utils.log)

**Comment by VishnuEaswaran** [comment]
Zombie issue. Linux built fixed and working for longtime now.
