### ISSUE TITLE
Request: Need 'git' in docker image

### ISSUE THREAD

**Issue by VishnuEaswaran** [adhuliya/ajit-toolchain#15]
I request to include 'git' package built into our Docker image. When it comes to Operating System build using BR2, some of the packages are fetched using git.

**Comment by adhuliya** [comment]
Okay. You can go ahead and add git in the docker file along with other packages. I will add it to the marshal once things stabilize there. Till then let this issue be open.

**Comment by VishnuEaswaran** [comment]
`git` added in ajit-linux branch.
