### ISSUE TITLE
toolchain build failed

### ISSUE THREAD

**Issue by saurabhb17** [adhuliya/ajit-toolchain#2]
running setup.sh grants me following error, right before running basic tests:

--------------------------------------------------------------------------------------
Updating the AJIT code for GDB.
Updating                       : include/opcode/sparc.h ...     Done.
Updating                       : opcodes/sparc-opc.c ...        Done.
Updating                       : opcodes/sparc-dis.c ...        Done.

Building                       : updated BINUTILS ...           Done.
**Building                       : updated GDB ...                BUILD Error.**

Time stamp of tools after build (if any):
NEWASMTOOLBUILDDATE            : 2020-09-16 13:43:14.052712309 +0530 (POST-UPDATE Assembler build date and time)
NEWDISASMTOOLBUILDDATE         : 2020-09-16 13:43:12.544712650 +0530 (POST-UPDATE Disassembler build date and time)

AJITBUILDSTATUS                : OK. (File modification time based overall status of UPDATED code)

Running basic tests:
sparc-buildroot-linux-uclibc-as          -Av8                 add-arith-insns.s    to add-arith-insns.o ...
sparc-buildroot-linux-uclibc-objdump     -d                   add-arith-insns.o    to add-arith-insns.dis.s ...
sparc-buildroot-linux-uclibc-gdb         -batch -x /tmp/commands.gdb add-arith-insns.o    to add-arith-insns.gdbdis.s ...
./src/update-all-ajit-code-and-run-tests.sh: line 272: **sparc-buildroot-linux-uclibc-gdb: command not found**
sparc-buildroot-linux-uclibc-as          -Av8                 ccc-cswap.s          to ccc-cswap.o ...
sparc-buildroot-linux-uclibc-objdump     -d                   ccc-cswap.o          to ccc-cswap.dis.s ...
sparc-buildroot-linux-uclibc-gdb         -batch -x /tmp/commands.gdb ccc-cswap.o          to ccc-cswap.gdbdis.s ...
./src/update-all-ajit-code-and-run-tests.sh: line 272: **sparc-buildroot-linux-uclibc-gdb: command not found**

**Comment by VishnuEaswaran** [comment]
I ran the _setup_ script now after pulling the latest changes. I didn't face any issues.
**build Environment**: Ubuntu:16.04 image-based container with the help of Docker.

**LOG FILE**: [link](https://drive.google.com/file/d/1TgbHluvAcq0D37MvXocjspOT0TR_aiRp/view?usp=sharing)

**Comment by saurabhb17** [comment]
libncurses5-dev and libncursesw5-dev libraries were missing. GBD is building properly now.

**Comment by adhuliya** [comment]
Although the vanilla Ubuntu 16.04 has sufficient packages to setup the binutils that we use, we need a complete list of dependencies with versions that are known to work. I am looking into how this can be done to avoid most future troubles.

**Comment by abhijatv** [comment]
Use ubuntu 12.04. Also The build script compares time stamps of a previous build with current build. This will fail since there is no previous build. I'll fix the build script.

But a build of binutils in the standard gnu style of configure ... make ... make install should work.
Please build first one like that.

Abhijat
