### ISSUE TITLE
Error creating tools

### ISSUE THREAD

**Issue by VishnuEaswaran** [adhuliya/ajit-toolchain#3]
Running **scons** in the tools directory fails. Error message hints missing AHIR_RELEASE env variable. Looking further, noticed it being used in the _exports.sh_ script, but not defined anywhere.

possible issue: missing AHIR source

**[log file](https://drive.google.com/file/d/1YTVfJy7B04HVBLzacHbcWKVVG_nS4iHA/view?usp=sharing)**

**Comment by adhuliya** [comment]
Yes. I had a similar discussion with Prof. Madhav, as I faced a similar issue while compiling ajit_C_system_model. I have a copy of Ahir build and its sources now. I will test and push it into the project. Let me know if you face any error then.

**Comment by adhuliya** [comment]
commit 468af9e in branch `marshal` has a folder `ahir_release` now. (not yet tested though)

**Comment by adhuliya** [comment]
Refer marshal branch to see how to compile the ajit tools successfully.
