### ISSUE TITLE
Changes for linux image creation

### ISSUE THREAD

**Issue by saurabhb17** [adhuliya/ajit-toolchain#4]
Remove " / " at the start of line 8 of  ../from_ajit_repo/os/Ajit_linux/linux_boot/compile.sh

Removing this resolves an error else the script treats **mmapToBin** utility as a directory.

To invoke _mmapToBin_ and _mmapToAssyU64_ utilities in the above script, the bashrc file from ajit_release also needs to be sourced first.

After doing above changes, the linux image is created properly([verified](https://drive.google.com/file/d/127Cwm6DgSCZH4n2ZBuQkK6IIeO1IuZRZ/view?usp=sharing) on the FPGA card as well).

**Comment by adhuliya** [comment]
@VishnuEaswaran please verify and close this issue after merging in the changes (if needed).

**Comment by saurabhb17** [comment]
@adhuliya Suggested changes will be merged in few days

**Comment by saurabhb17** [comment]
Issue resolved in commit f267229
