### ISSUE TITLE
buildroot.2014.08 depedencies list

### ISSUE THREAD

**Issue by adhuliya** [adhuliya/ajit-toolchain#5]
A complete list of dependencies (with minimal versions that work) for buildroot.2014.08 is needed. This will help us move to any linux distribution in the near future and add certainty (and debug ability) to the current build process.
(This will also help us know why the buildroot doesn't compile on 18.04)

**Comment by VishnuEaswaran** [comment]
Thanks @adhuliya ! 

I believe this is what we are looking for - [link](https://buildroot.org/downloads/manual/manual.html#requirement-mandatory)

**Comment by adhuliya** [comment]
@VishnuEaswaran yes certainly for our version of buildroot + some other tools that we add to our build process. Moreover knowing the reason why buildroot.2014.08 doesn't compile on 18.04 even after meeting all the dependencies may be useful (though not a priority). Moving directly to 20.04 container image could be tried (again not a priority work). With docker containerization we can sidestep the latter issue but don't know for how long staying on 16.04 image would be wise.

**Comment by VishnuEaswaran** [comment]
I am open to anything but as you mentioned lets prioritise wisely. Let the first milestone be a docker image for 16.04 and then figure out the rest.

**Comment by adhuliya** [comment]
This issue will be handled with the issue #8 
Let the issue be open till then as a reminder.

**Comment by adhuliya** [comment]
The marshal branch resolves this issue.
