### ISSUE TITLE
Moving to docker containers

### ISSUE THREAD

**Issue by adhuliya** [adhuliya/ajit-toolchain#6]
Docker containers are great tools to provide reliability of deployment given any OS (Linux, Windows, and MacOS). They are also easy to setup. I have started this issue to initiate a light discussion on this front. If we all feel there are enough reasons to use docker containers, I can do so from my end.

Advantages of using docker containers,
1. The same build process will work on any OS. Hence no more build errors once the build process
    is tested and updated in the repo.
2. The current dependencies of the build process will be neatly recorded for all future purposes.
3. We will be forced to record any non-trivial dependencies in the docker files, which will also work as dependency 
    documentation.
4. The system will be reliably reproducible for decades to come and the docker images can be periodically released
    providing a complete system with no setup needed by the end user.

What are your thoughts?

**Comment by VishnuEaswaran** [comment]
I support the suggestion. It is the best way to resolve the dependency/environment setting up issue.
In fact my system is Arch based and hence our builds had issues. So I put together an image with base layer as [Ubuntu:16.04](https://hub.docker.com/layers/ubuntu/library/ubuntu/16.04/images/sha256-f3be6e2f7036fcd04625964f7ac2272900103194a9ebc1d81d7ad1e349c3151f?context=explore). Then I added missing packages incrementally as they showed up missing while building. I have shared a list of packages I installed in this [issue](https://github.com/adhuliya/ajit-toolchain/issues/1#issue-693046726).

I am no expert with Docker but would like to chip in whatever I can to fix our issue.

**Comment by adhuliya** [comment]
It seems you have already begun with the docker setup. I think you can start by adding the `/Dockerfile` that you have already built on the base layer `Ubuntu:16.04` to the top level of the project (possibly with appropriate comments for others to understand). Then I can keep contributing to it in my spare time adding and testing one component at a time. Later we can use <hub.docker.com> to publish our image to the public. (For now we may add a line in our `/README.md` that the `/Dockerfile` present is a work in progress.)

**Comment by VishnuEaswaran** [comment]
I will initiate this :+1:

**Comment by VishnuEaswaran** [comment]
should I start a branch for it ?

**Comment by adhuliya** [comment]
That seems to be a clean idea. Sure.

**Comment by adhuliya** [comment]
This issue is taking more time than required. I am working on it with @abhijatv on the branch `marshal`.
Let the issue remain open till then as a reminder.

**Comment by VishnuEaswaran** [comment]
I already have the docker setup files in place. Testing is almost done. There is a pending issue while compiling Ajit linux. Please try the toolchain build when you get time.

**Comment by adhuliya** [comment]
You can commit that in the branch that you are working on and mention this issue in the commit msg with "#this-issue-id". Others can then know the commit corresponding to the issue here and pick it from there.

**Comment by VishnuEaswaran** [comment]
So I have to tag the issue number with all the commits right? Roger that :+1:

**Comment by adhuliya** [comment]
Just mention the issue number in the commit msg and it will automatically show up here in our discussions.

**Comment by adhuliya** [comment]
The marshal branch resolves this issue. It needs some more improvements and then it can be merged with the master branch.
